### ISSUE TITLE
Display more info on markers

### ISSUE THREAD

**Issue by Seercat3160** [TechnicJelle/BlueMapOfflinePlayerMarkers#2]
**Feature request:** Add additional info when a marker is clicked, such as:

- [x] Name
- [ ] Time the player logged out

**Comment by Seercat3160** [comment]
I'll work on this in Seercat3160:htmlmarkers

**Comment by TechnicJelle** [comment]
Name implemented by Blue in #21

**Comment by TechnicJelle** [comment]
And the last one was just implemented in 6d817177fbcd7a22b618f5156396f4cb6f82e75c:
![image](https://user-images.githubusercontent.com/22576047/212554019-9f05472d-e159-4e14-886b-83c19bf52a77.png)
