### ISSUE TITLE
Server with online-mode disabled shows markers incorrectly

### ISSUE THREAD

**Issue by BuIlDaLiBlE** [TechnicJelle/BlueMapOfflinePlayerMarkers#29]
There seems to be a problem displaying the markers when skins cannot be found. Take a look at my map: https://bpnet.work/bluemap.
I do get "doesn't have a skin" for every player in the game as the server is in offline mode, but I have SkinsRestorer plugin so maybe it's possible to integrate the plugin with that or at least show the default Steve heads? :X

**Comment by TechnicJelle** [comment]
Fixed the Steve head fallback not working on BlueMaps hosted on a subdirectory of a website in 74616f27c3dec642da9d97eb460402da9372e441
You can download it here: https://github.com/TechnicJelle/BlueMapOfflinePlayerMarkers/releases/tag/v2.5
Thanks for the bug report! :)
