### ISSUE TITLE
Markers not showing up as greyed out.

### ISSUE THREAD

**Issue by Wolfie713** [TechnicJelle/BlueMapOfflinePlayerMarkers#42]
Updated the main BlueMap plugin, and the offline markers are fully colored as though the players are online vs being greyed out.

**Comment by TechnicJelle** [comment]
Which BlueMap version are you using now, exactly? Please give me the exact version number.

The markers not being greyed out is a symptom of the custom style not applying for one reason or another.
It could have failed to copy to the webapp, it could have failed to register, it could have failed to load in your browser, or the style could have a bug.

When you open your map and open your browser's devtools, can you see a `bmopm.css` file in the `<head>` and a `bmopm.js` in the `<body>`, like so:
![image](https://github.com/TechnicJelle/BlueMapOfflinePlayerMarkers/assets/22576047/a304782e-bbc8-46e8-92fc-8532c6f331ca)

**Comment by Wolfie713** [comment]
BlueMap-3.21-paper.jar

Not seeing the bmopm files, though they are in the folder (on the server).

Just tried "/bluemap debug cache" to see if that would help and it didn't make a difference.

**Comment by TechnicJelle** [comment]
If they're not in the HTML like on my screenshot, they're likely not being registered properly...

Are you perhaps hosting your map with an external webserver?
Please try going to `http://your.blue.map/assets/bmopm.css`.
You should see something like this:
![image](https://github.com/TechnicJelle/BlueMapOfflinePlayerMarkers/assets/22576047/926221ff-34fd-4068-b7c8-c5186587da24)

If you don't, there is a problem in your setup somewhere.

Please also send me what `http://your.blue.map/settings.json` shows.

**Comment by TechnicJelle** [comment]
Oh, if a reload fixed it, then it's definitely to do with the registering...
I believe I had fixed that issue, but it may not have been released yet.

**Comment by TechnicJelle** [comment]
Ah, no… I haven't.
Could you please go to the [Actions](https://github.com/TechnicJelle/BlueMapOfflinePlayerMarkers/actions/workflows/maven.yml) tab and download the latest release from there?

**Comment by Wolfie713** [comment]
Do you mean for this repository?  When I click on the word "Actions" in your comment, it takes me to a file "maven.yml?"  Not sure what to do with that.

**Comment by TechnicJelle** [comment]
https://github.com/TechnicJelle/BlueMapOfflinePlayerMarkers/assets/22576047/5a961080-ea6a-430a-ac83-a45740927bc4

Click the `artifact` there, and you'll get a zip with the latest of the latest version.
It should work in that one.

**Comment by Wolfie713** [comment]
Okay, did that.  Will let you know what else breaks from it.  🤪

Thanks.

**Comment by TechnicJelle** [comment]
Thanks, keep me posted.
I'll close this issue now. If the icons stay coloured, please reopen it.
If there are other problems, please create a new issue for those (in this repo :stuck_out_tongue_winking_eye:).

**Comment by Wolfie713** [comment]
> If there are other problems, please create a new issue for those (in this repo 😜).

I'll be sure to do that, even if it's for the Death Markers one...  🤪
