### ISSUE TITLE
Add config option to specify where to get the player icon from

### ISSUE THREAD

**Issue by TechnicJelle** [TechnicJelle/BlueMapOfflinePlayerMarkers#8]
```yaml
#The place to get the playerhead icons from. Leave empty to use BlueMap's own files
#Accepted variables: {UUID}, {USERNAME}
# Examples:
#  playerheadsAPI: ""
#  playerheadsAPI: "https://crafatar.com/avatars/{UUID}.png?size=8&overlay=true"
playerheadsAPI: ""
```

**Comment by Seercat3160** [comment]
I don't think that the player's username should be a placeholder value, as afaik it's not possible for services to get things using the username anymore.

[Crafatar:](https://crafatar.com/#meta-usernames)
> About Usernames
>
> By disabling a legacy API in 2018, Mojang has made it practically impossible for Crafatar to support usernames. Please use UUIDs instead!
>
> All usernames are rejected.

**Comment by TechnicJelle** [comment]
I know that at least https://minotar.net/ still supports usernames, and I want to support offline servers that cannot rely on UUIDs too. (I do _not_ condone piracy, though!)

**Comment by Seercat3160** [comment]
That makes sense. Maybe we should also add a value for the config that makes it use the API of SkinRestorer or something.
